pipeline {
    agent any
    stages {
        stage('build'){
            steps {
                sh 'echo Hello World'
                echo "Build number is ${currentBuild.number}"
            }
        }
    }
}
