volumes:
  jenkins_home:

services:
  jenkins:
    container_name: jenkins
    # build: .
    image: jenkins/jenkins:2.516.3-jdk21
    restart: on-failure
    environment:
      - JENKINS_ADMIN_ID=${JENKINS_ADMIN_ID}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"

