volumes:
  jenkins_home:

networks:
  jenkins:

services:
  jenkins:
    container_name: jenkins
    build: .
    # image: jenkins/jenkins:2.516.3-jdk21
    restart: unless-stopped
    environment:
      - JENKINS_ADMIN_ID=${JENKINS_ADMIN_ID}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
      - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins 
    ports:
      - "8080:8080"

  jenkins-agent:
    container_name: jenkins-agent
    image: jenkins/ssh-agent:jdk21
    restart: unless-stopped
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
    networks:
      - jenkins 
    ports:
      - "22:22"

